dist: trusty
language: php

php:
#  - 7.3
#  - 7.2
  - 7.1

addons:
  chrome: stable
#  apt:
#    packages:
#      - chromium-chromedriver

services:
  - mysql

env:
  global:
    - DRUPAL_BUILD_DIR=$TRAVIS_BUILD_DIR/../drupal
    - SIMPLETEST_DB=mysql://root:@127.0.0.1/drupal
    - PATH="$PATH:$HOME/.composer/vendor/bin"
  jobs:
#    - DRUPAL_CORE=8.6.x
#    - DRUPAL_CORE=8.7.x
    - DRUPAL_CORE=8.8.x

jobs:
  fast_finish: true

mysql:
  database: drupal
  username: root
  encoding: utf8

# Cache composer downloads.
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  # Update composer.
  - composer self-update

  - composer global require "hirak/prestissimo:^0.3"
  - composer global require "drupal/coder:8.3.*"
  - phpcs --config-set installed_paths $HOME/.composer/vendor/drupal/coder/coder_sniffer

install:
  - apt-get --only-upgrade install google-chrome-stable
  # Create the database.
  - mysql -e 'create database drupal'

  # Download Drupal 8 core from the Github mirror because it is faster.
  - git clone --branch $DRUPAL_CORE --depth 1 https://github.com/drupal/drupal.git $DRUPAL_BUILD_DIR

  # Reference the module in the build site.
  - ln -s $TRAVIS_BUILD_DIR $DRUPAL_BUILD_DIR/modules/commerce_yandex_checkout

  # Bring in the module dependencies without requiring a merge plugin. The
  # require also triggers a full 'composer install'.
  - composer --working-dir=$DRUPAL_BUILD_DIR require drupal/commerce:^2.14
  - composer --working-dir=$DRUPAL_BUILD_DIR require yandex-money/yandex-checkout-sdk-php:^1.5

  # For Drupal < 8.8 we have to manually upgrade zend-stdlib to avoid PHP 7.3
  # incompatibilities.
  - if [[ "$DRUPAL_CORE" = "8.6.x" || "$DRUPAL_CORE" = "8.7.x" ]];
      then composer --working-dir=$DRUPAL_BUILD_DIR require zendframework/zend-stdlib:3.2.1;
    fi

  # For Drupal < 8.8 we have to manually upgrade phpunit to avoid PHP 7.3
  # incompatibilities.
  - if [[ "$DRUPAL_CORE" = "8.6.x" || "$DRUPAL_CORE" = "8.7.x" ]];
      then composer --working-dir=$DRUPAL_BUILD_DIR run-script drupal-phpunit-upgrade;
    fi

  # Start a web server on port 8888, run in the background; wait for
  # initialization.
  - nohup php -S localhost:8888 > /dev/null 2>&1 &

  # Export web server URL for browser tests.
  - export SIMPLETEST_BASE_URL=http://localhost:8888

  # Install Chromedriver.
  - mkdir travis-chromedriver
  - CHROMEDRIVER_VERSION=$(wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE -qO-)
  - wget http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d travis-chromedriver && rm -f chromedriver_linux64.zip
  - chmod a+x travis-chromedriver/chromedriver
  - export PATH=$PWD/travis-chromedriver:$PATH
  - chromedriver --version
  - google-chrome-stable --version

before_script:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
  - export MINK_DRIVER_ARGS_WEBDRIVER='["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless","--no-sandbox","--disable-dev-shm-usage","--disable-extensions"]}}, "http://localhost:9515"]'
  - chromedriver &

script:
  - $DRUPAL_BUILD_DIR/vendor/bin/phpunit --configuration $DRUPAL_BUILD_DIR/core --group commerce_yandex_checkout --verbose
  - phpcs --report=full --colors --standard="Drupal,DrupalPractice" --extensions="php,module,inc,install,test,profile,theme" $TRAVIS_BUILD_DIR
